github: [chris-short]
patreon: devopsish
custom: ["paypal.me/devopsish", devopsish.com, chrisshort.net, nomedium.dev, kubernetesreadme.com, kubenews.net, devopsreadme.xyz, devopsnewsletters.com, padbury.app, crashloopbackoff.dev]