github: [chris-short]
patreon: devopsish
custom: ["paypal.me/devopsish", devopsish.com, chrisshort.net, nomedium.dev, kubereadme.com, kubenews.net, devopsreadme.com, devopsnewsletters.com, crashloopbackoff.dev]