baseURL = "https://nomedium.dev/"
languageCode = "en"
defaultContentLanguage = "en"
title = "No More Medium. Build Your Own Site, Please."
theme = "stip"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS"]

[Author]
    name = "No Medium"
    bio = "Medium is Bad. Stop Using It."

[params]

    [params.colors]
        background = "#333333"
        circle = "#3942ba"
        foreground = "#c7d0fc"
        hover = "#cd6cf7"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/chris-short/nomedium.dev"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/ChrisShort"
      
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/thechrisshort/"

    [[params.links]]
        iconset = "fas"
        icon = "newspaper"
        title = "DevOps'ish"
        url = "https://devopsish.com/"
