[build]
publish = "public"
command = "hugo --gc --minify --config config.toml"

[context.production.environment]
HUGO_VERSION = "0.64.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "git submodule update --rebase --remote && hugo --gc --minify --enableGitInfo --config config.toml"

[context.split1.environment]
HUGO_VERSION = "0.64.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "git submodule update --rebase --remote && hugo -v --gc -DF --config config-preview.toml"
[context.deploy-preview.environment]
HUGO_VERSION = "0.64.0"
# Skip all post processing in deploy previews,
# ignoring any other settings
[context.deploy-preview.processing]
  skip_processing = true

[context.branch-deploy]
command = "git submodule update --rebase --remote && hugo -v --gc -DF"
[context.branch-deploy.environment]
HUGO_VERSION = "0.64.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://nomedium.netlify.app/*"
  to = "https://nomedium.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://nomedium.dev"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"